/*
  # Create skills table

  1. New Tables
    - `skills`
      - `id` (bigint, primary key)
      - `name` (text, unique) - skill level name
      - `description` (text) - description of skill level
      - `order_index` (smallint) - for ordering skills from beginner to elite
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on `skills` table
    - Add policy for public read access
    - Add policy for admin-only write access
*/

CREATE TABLE IF NOT EXISTS skills (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL,
  description text,
  order_index smallint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
  ON skills
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Admins can manage skills"
  ON skills
  FOR ALL
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ));

-- Insert default skill levels
INSERT INTO skills (name, description, order_index) VALUES
  ('Beginner', 'New to the sport, learning basic rules and techniques', 1),
  ('Intermediate', 'Comfortable with basic skills, developing consistency', 2),
  ('Advanced', 'Strong fundamental skills with tactical understanding', 3),
  ('Competitive', 'High-level play with advanced techniques and strategies', 4),
  ('Elite', 'Tournament-level play with specialized skills', 5)
ON CONFLICT (name) DO NOTHING;