/*
  # Add sports table for gym management

  1. New Tables
    - `sports`
      - `id` (bigint, primary key)
      - `created_at` (timestamp with time zone)
      - `name` (text, unique, not null)
      - `active` (boolean, default true)
      - `description` (text, nullable)

  2. Security
    - Enable RLS on `sports` table
    - Add policy for public read access
    - Add policy for admin management

  3. Data
    - Insert initial sports data
*/

CREATE TABLE IF NOT EXISTS sports (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text UNIQUE NOT NULL,
  active boolean DEFAULT true NOT NULL,
  description text
);

ALTER TABLE sports ENABLE ROW LEVEL SECURITY;

-- Policies for sports table
CREATE POLICY "Enable read access for all users"
  ON sports
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Admins can manage sports"
  ON sports
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.auth_id = uid() AND users.is_admin = true
    )
  );

-- Insert initial sports data
INSERT INTO sports (name, description) VALUES
  ('Volleyball', 'Indoor volleyball leagues with various skill levels'),
  ('Badminton', 'Singles and doubles badminton competitions'),
  ('Basketball', 'Competitive basketball leagues'),
  ('Pickleball', 'Fast-growing racquet sport combining elements of tennis, badminton, and ping-pong')
ON CONFLICT (name) DO NOTHING;

-- Add sport_id foreign key to seasons table if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'seasons' AND column_name = 'sport_id'
  ) THEN
    ALTER TABLE seasons ADD COLUMN sport_id bigint REFERENCES sports(id);
  END IF;
END $$;